### PR TITLE
fix broken usafacts tests to read from the proper directories

### PR DESCRIPTION
**Pull request by sgsmob**
`usafacts` was trying to read/write to/from `receiving` when run in the `tests` directory rather than `../receiving`.  The tests now pass.

### CODE REVIEW

**Comment by jingjtang** [comment]
Hi @sgsmob, I think a better way to solve this is to add a `./receiving` folder under tests, then we will stored the output from tests under `usafacts/tests/receiving` and check those file there. 

The current solution seems weird. Since the receiving dir in `usafacts/tests/params.json` is stilled defined as `usafacts/tests/receiving`, but in `test_run.py` we check the output from `usafacts/receiving`.

**Comment by sgsmob** [comment]
Changed to add the `./receving` directory.

**Review by jingjtang — DISMISSED** [review]
All unit tests passed

**Review by krivard — DISMISSED** [review]

**Comment by krivard** [comment]
Oh ffs. @korlaxxalrok this PR seems to trigger the same pytest/asteroid "recursion limit exceeded" problem as we were having in JHU. Tests seem to pass in Jingjing's environment so I think we're okay to disable them here the same way. If you agree, go ahead and do that so we can unblock Mike.

Afterwards, could you work with @benjaminysmith to figure out a more permanent solution?

**Comment by sgsmob** [comment]
Yes I observed the recursion limit issue.  FWIW I have a pylint extension on my IDE and I corrected the mistakes there.

**Comment by korlaxxalrok** [comment]
I'll disable linting for now, and then spend some time looking at an actual fix.

**Comment by korlaxxalrok** [comment]
@krivard @sgsmob Linting is disabled.

**Review by krivard — APPROVED** [review]

**Pull request merged**
