### PR TITLE
Adjust JHU validation params

### PR DESCRIPTION
**Pull request by nmdefries**
### Description
Add a `validation` section to the `jhu` `params.json.template`. Supersedes #752.

### Fixes 
- Partially addresses #725

### CODE REVIEW

**Comment by krivard** [comment]
Did you branch off of sgsmob:jhu? If so then we can just say this PR supersedes that one, unless there's something in the #752 reviews you want to keep

**Comment by nmdefries** [comment]
> Did you branch off of sgsmob:jhu?

Yep, superseding is fine. I'll update this PR and comment on #752 to reflect that.

**Comment by nmdefries** [comment]
Hey @rumackaaron pinging you for review. This is just a slight modification of #752 that you'd looked at before.

**Comment by rumackaaron** [comment]
When I run it, I get 50 errors `check_test_vs_reference_avg_changed failed` for deaths incidence prop and num at the county and msa level. I don't know if this is expected or desired

**Comment by nmdefries** [comment]
> I get 50 errors check_test_vs_reference_avg_changed failed for deaths incidence prop and num at the county and msa level. I don't know if this is expected or desired

The overactive county errors were addressed in PR #1051 that you looked at recently. This branch didn't have that change added, but I've merged in main so we can see how that behaves with the updated params file here.

On my end, I get ~20 `check_test_vs_reference_avg_changed failed` for a variety of dates, signals, and geo types. And this is expected/desired.

**Review by rumackaaron — APPROVED** [review]
Ok, looks good then!

**Pull request merged**
