### PR TITLE
Add JSON check to CI

### PR DESCRIPTION
**Pull request by chinandrew**
### Description
Inspired by [this slack thread](https://delphi-org.slack.com/archives/C0130CSQRN3/p1610919922003300) to catch any bad json. I've verified that the bad usafacts json would have been caught by this.

Note that the last item in the list is the problematic json file (safegraph_patterns) in the below example:
```
Run python3 -c "import json; from pathlib import Path
  python3 -c "import json; from pathlib import Path
  for i in Path('.').glob('**/*.json*'):
      if '/env/' not in str(i):
          print(i)
          json.load(open(str(i)))"
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.7/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.7/x64/lib
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 12 column 1 (char 276)
combo_cases_and_deaths/params.json.template
combo_cases_and_deaths/tests/params.json.template
google_symptoms/params.json.template
google_symptoms/tests/params.json.template
usafacts/params.json.template
usafacts/tests/params.json.template
google_health/params.json.template
google_health/tests/params.json.template
validator/params.json.template
ansible/templates/google_symptoms-params-prod.json.j2
ansible/templates/safegraph-params-prod.json.j2
ansible/templates/sir_complainsalot-params-prod.json.j2
ansible/templates/jhu-params-prod.json.j2
ansible/templates/google_health-params-prod.json.j2
ansible/templates/google_health-params-test.json.j2
ansible/templates/nchs_mortality-params-prod.json.j2
ansible/templates/quidel_covidtest-params-prod.json.j2
ansible/templates/changehc-params-prod.json.j2
ansible/templates/hhs_hosp-params-prod.json.j2
ansible/templates/safegraph_patterns-params-prod.json.j2
ansible/templates/usafacts-params-prod.json.j2
claims_hosp/params.json.template
claims_hosp/tests/params.json.template
hhs_hosp/params.json.template
hhs_hosp/tests/params.json.template
quidel/params.json.template
quidel/tests/params.json.template
changehc/params.json.template
changehc/tests/params.json.template
sir_complainsalot/params.json.template
sir_complainsalot/tests/params.json.template
safegraph/params.json.template
safegraph/tests/params.json.template
jhu/params.json.template
jhu/tests/params.json.template
cdc_covidnet/params.json.template
cdc_covidnet/tests/params.json.template
cdc_covidnet/tests/cache_test/networkid_2_catchmentid_2.json
cdc_covidnet/tests/cache_test/networkid_3_catchmentid_21.json
cdc_covidnet/tests/cache_test/networkid_2_catchmentid_14.json
cdc_covidnet/tests/cache_test/networkid_2_catchmentid_1.json
cdc_covidnet/tests/cache_test/networkid_3_catchmentid_15.json
cdc_covidnet/tests/cache_test/networkid_2_catchmentid_9.json
cdc_covidnet/tests/cache_test/networkid_2_catchmentid_3.json
cdc_covidnet/tests/cache_test/networkid_2_catchmentid_17.json
cdc_covidnet/tests/cache_test/init.json
cdc_covidnet/tests/cache_test/networkid_2_catchmentid_4.json
cdc_covidnet/tests/cache_test/networkid_2_catchmentid_11.json
cdc_covidnet/tests/cache_test/networkid_3_catchmentid_5.json
cdc_covidnet/tests/cache_test/networkid_2_catchmentid_7.json
cdc_covidnet/tests/cache_test/networkid_3_catchmentid_8.json
cdc_covidnet/tests/cache_test/networkid_2_catchmentid_20.json
_template_python/params.json.template
_template_python/tests/params.json.template
hhs_facilities/params.json.template
hhs_facilities/tests/params.json.template
safegraph_patterns/params.json.template
Error: Process completed with exit code 1.
```

### Changelog
Itemize code/test/documentation changes and files added/removed.
- Add a workflow that runs through all the json files and tried to read them.
- Fixed a safegraph json format issue

### CODE REVIEW

**Review by benjaminysmith — APPROVED** [review]
Thanks!!

**Comment by krivard** [comment]
@chinandrew was there something in particular you wanted from Brian or should I go ahead and merge?

**Comment by chinandrew** [comment]
> @chinandrew was there something in particular you wanted from Brian or should I go ahead and merge?

Nope, should be good to merge.

**Review by korlaxxalrok — APPROVED** [review]
👍 :shipit:

**Pull request merged**
