### PR TITLE
[fb-package] Reduce memory usage by dropping unused columns

### PR DESCRIPTION
**Pull request by nmdefries**
### Description
We carry many extraneous columns along during the aggregation process. Removing those and only keeping variables directly used in calculations plus supporting columns (zip code, day) should reduce memory usage.

Tests pass as expected; pipelines before and after this change produce the same output.

### Changelog
- Use `select` to keep necessary columns in `aggregate_indicators`
- Auto-format + spelling fixes (second commit; not substantive)

### CODE REVIEW

**Review by capnrefsmmat — APPROVED** [review]
looks good, although I was getting used to those spelling mistakes

**Comment by krivard** [comment]
conflicts?

**Comment by capnrefsmmat** [comment]
easy fix (@nmdefries should confirm I resolved correctly)

**Comment by nmdefries** [comment]
Looks good

**Pull request merged**
