### PR TITLE
[cpr] Activate vaccination signals in production

### PR DESCRIPTION
**Pull request by krivard**
### Description
Turn on vaccination signals in the DSEW-CPR indicator

### Changelog
Itemize code/test/documentation changes and files added/removed.
- production params template in ansible

### CODE REVIEW

**Comment by krivard** [comment]
confirm for me that this is the correct signals set 🙏

**Comment by Ananya-Joshi** [comment]
Do we want 'total' and 'positivity' (these are unrelated to the vaccination signals). For reference: 
Screen Shot 2022-02-28 at 1 33 33 PM

**Comment by krivard** [comment]
Not yet -- there's a bunch of changes to the testing signals [that came up in review](https://github.com/cmu-delphi/covidcast-indicators/issues/1513)

**Comment by Ananya-Joshi** [comment]
Ah, now I understand - confirming the signals set from the vaccination side.

**Pull request merged**
