### PR TITLE
[fb-package] Split `vaccine_barriers` indicator into vaccinated and tried versions

### PR DESCRIPTION
**Pull request by nmdefries**
### Description
Provide version of `vaccine_barriers` indicators where respondents who've been vaccinated and those who have unsuccessfully tried to get vaccinated are reported separately.

### Changelog
- Define new `v_vaccine_barrier_<reason>_has` and `v_vaccine_barrier_<reason>_tried` variables
- Report indicators in API and contingency tables

### CODE REVIEW

**Review by capnrefsmmat — APPROVED** [review]
Looks good; have the names been approved by Facebook for consistency with UMD?

**Comment by nmdefries** [comment]
Yup, the names are directly from FB's indicator spreadsheet.

**Comment by krivard** [comment]
When should I deploy these?

**Comment by nmdefries** [comment]
This is ready to go whenever.

**Comment by krivard** [comment]
Okay, will deploy Monday for Tuesday morning first run.

**Pull request merged**
