### PR TITLE
Add `percent_of_expected_deaths` signal and dry-run mode to NCHS mortality data pipeline

### LINKED ISSUE #119: Consider adding vintage NCHS mortality data from the CDC
Roni forwarded Alex and I an archive file for https://www.cdc.gov/nchs/nvss/vsrr/COVID19/index.htm.

Roni says:

> official Covid-related mortality data (alas, state-level only and with ~2 week backfill)

Not urgent, but may prove useful to modeling/forecasting.

### PR DESCRIPTION
**Pull request by jingjtang**
Closes #119 

- Add `percent_of_expected_deaths` signal
  - values are around 1
  - no metric level 2 (`num` or `prop`) for this signal, just report the raw values
- Add a dry-run mode, so that the test cases are independent from the `token`

I noticed that they actually update the dataset every weekday. (The column `data_as_of` is always the date of today) Maybe we want to run the pipeline everyday in order to get the backfill info.(The pipeline will run for only less than 10 seconds every time)

### CODE REVIEW

**Comment by dshemetov** [comment]
Checking code coverage in the tests:
```
----------- coverage: platform linux, python 3.8.5-final-0 -----------
Name                                                                                       Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------------------------------------------------
/home/dskel/Code/covidcast-indicators-1/nchs_mortality/delphi_nchs_mortality/pull.py          38      9    76%   46-48, 54-55, 76, 81, 90-91
/home/dskel/Code/covidcast-indicators-1/nchs_mortality/delphi_nchs_mortality/run.py           72      6    92%   37-39, 123, 141-142, 146
------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                        127     16    87%
```
* There are a few ValueExceptions in `pull.py` that haven't been tested: 54-55, 76, 81, 90-91. It may be worth it to add a simple test case for each of those. 
* The `run.py` lines are mostly archiver cases, which I think we can assume to have been tested as part of the archiver util.

**Comment by dshemetov** [comment]
Not part of this set of commits, so maybe this belongs to another issue, but I'm wondering if the lines 63-67 in `pull.py` are necessary. Doesn't `groupby` automatically group the unique values and make a multi-index?
```
    state_list = df["state"].unique()
    date_list = df["timestamp"].unique()
    index_df = pd.MultiIndex.from_product(
        [state_list, date_list], names=['state', 'timestamp']
    )
    df = df.groupby(
            ["state", "timestamp"]).sum().reindex(index_df).reset_index()
```

**Comment by jingjtang** [comment]
> Not part of this set of commits, so maybe this belongs to another issue, but I'm wondering if the lines 63-67 in `pull.py` are necessary. Doesn't `groupby` automatically group the unique values and make a multi-index?
> 
> ```
>     state_list = df["state"].unique()
>     date_list = df["timestamp"].unique()
>     index_df = pd.MultiIndex.from_product(
>         [state_list, date_list], names=['state', 'timestamp']
>     )
>     df = df.groupby(
>             ["state", "timestamp"]).sum().reindex(index_df).reset_index()
> ```

This is added in case the values for some states are missing for certain dates.

**Comment by dshemetov** [comment]
> This is added in case the values for some states are missing for certain dates.

I see, so this is to make sure that every state has the same number of reported dates?

**Comment by jingjtang** [comment]
> > This is added in case the values for some states are missing for certain dates.
> 
> I see, so this is to make sure that every state has the same number of reported dates?

Yes.

**Comment by dshemetov** [comment]
Should `FIPS` here be replaced by `state`?
```
    # each FIPS has same number of rows
    if (len(days_by_states) > 1) or (days_by_states[0] != len(unique_days)):
        raise ValueError("Differing number of days by fips")
```

**Review by dshemetov — COMMENTED** [review]
Mostly small linter fixes here.

My only other comment is that the weekly vs daily updates change was tough to understand reading this thread or the code. I think adding some elaboration to the documentation for that would help people coming to this codebase later. 

Other than that, all tests pass, so after the linter fixes, I think this PR is good to go.

**Comment by krivard** [comment]
@dshemetov Agree on documentation -- @jingjtang can you add a section to DETAILS.md describing the details of:
* how often we check for updates from NCHS
* how those changes are tracked
* how often we upload to the API
* how that changeset is generated

**Comment by dshemetov** [comment]
@jingjtang See my first comment for code coverage concerns. I think we should try to make sure we have tests that cover all the code lines, so we don't have surprises down the road. In particular:
`run.py`
- lines 37-39
`pull.py`
- lines 76, 81, 90-91

If you're absolutely sure those work, I can relent on this issue. Just trying to enforce some testing consistency.

**Comment by jingjtang** [comment]
> @jingjtang See my first comment for code coverage concerns. I think we should try to make sure we have tests that cover all the code lines, so we don't have surprises down the road. In particular:
> 
> * `run.py`
>   
>   * lines 37-39
> * `pull.py`
>   
>   * lines 76, 81, 90-91
> 
> If you're absolutely sure those work, I can relent on this issue. Just trying to enforce some testing consistency.

Added a new test case for missing cols. As for others:
- `run.py` 37-39 is added for the automation usage, will check with @korlaxxalrok later
- `pull.py` They are just final sanity checks for the previous code.

**Comment by dshemetov** [comment]
LGTM!

**Review by dshemetov — APPROVED** [review]

**Pull request merged**
