### PR TITLE
Prepare Sir Complainsalot for a staging deployment

### PR DESCRIPTION
**Pull request by korlaxxalrok**
### Description
Adds deployment necessities for deploying Sir Complainsalot.

### Changelog
- Add prodution params template.
- Add variable pointer/encrypted variable.
- Tell Jenkins to build and deploy.

### CODE REVIEW

**Comment by korlaxxalrok** [comment]
@chinandrew I guess we probably need to run CI for `sir_complainsalot` as well?

**Comment by chinandrew** [comment]
> @chinandrew I guess we probably need to run CI for `sir_complainsalot` as well?

It doesnt have tests so not super critical, but linting would run.

**Review by chinandrew — APPROVED** [review]
:shipit::shipit::shipit:

Just out of curiosity, how was this previously deployed?

**Comment by korlaxxalrok** [comment]
I believe this is running on a standalone CMU machine and being deployed in some manual way. We may want to coordinate to shut down the currently running instance once this is ready to go to prod.

**Comment by korlaxxalrok** [comment]
@chinandrew Ok, we can add CI later if we want it. Going to merge this for now.

**Pull request merged**
