### PR TITLE
Improve on initial version of survey codebook and incorporate feedback

### PR DESCRIPTION
**Pull request by nmdefries**
### Description
Improve on #1071.

### Changelog
- Clarify README.
- Add timezone to metadata field descriptions.
- Write codebook to CSV in an Excel-friendly way.
- Add answer choice coding in json string format to be machine-readable.

### CODE REVIEW

**Comment by nmdefries** [comment]
Example of choices formatting: 

Screenshot from 2021-07-15 15-15-35

**Review by capnrefsmmat — APPROVED** [review]
Looks  good. When should we start finding a place to put the codebook on the website and writing documentation of it?

**Comment by nmdefries** [comment]
I have all the necessary pieces, just need to produce an updated codebook, which is fast. It could be ready to share as soon as tomorrow.

**Comment by nmdefries** [comment]
@krivard This is ready to merge.

**Pull request merged**
