### PR TITLE
Sync all deploy branches into main in prep for generating prod branch

### PR DESCRIPTION
**Pull request by krivard**
### Description
As recommended in #522, this PR will merge all deploy-* branches into main. Once it is merged, we will generate `prod` as a branch from main, and officially begin the new deployment scheme.

### Changelog
- deploy-changehc (3 ahead)
- deploy-jhu (0 ahead)
- deploy-usafacts (3 ahead)
- deploy-google_health (1 ahead)
- deploy-safegraph (2 ahead)
- ~deploy-quidel (13 ahead; conflicts)~ repaired-deploy-quidel (11 ahead)

### CODE REVIEW

**Comment by krivard** [comment]
@korlaxxalrok to check the ansible vault and verify that both changehc and quidel secrets are included.

**Comment by korlaxxalrok** [comment]
@krivard Secrets look good 👌

**Review by chinandrew — APPROVED** [review]
:shipit: :shipit: :shipit:

**Review by korlaxxalrok — APPROVED** [review]
LGTM 👍 🦜

**Comment by krivard** [comment]
Merged, created `prod` branch off of the resulting `main`, and enacted branch protection rules

**Pull request merged**
