### PR TITLE
Fix bug in sircal where a single day of data will fail when checking gaps

### PR DESCRIPTION
**Pull request by benjaminysmith**
### Changelog
- When gap days is empty, do not try to calculate the max gap.

### CODE REVIEW

**Comment by chinandrew** [comment]
Should it log something before continuing? (or instead set gap = 0 and run the rest of the code as normal)

**Comment by krivard** [comment]
@benjaminysmith ping

**Comment by benjaminysmith** [comment]
> Should it log something before continuing? (or instead set gap = 0 and run the rest of the code as normal)

Added a log line.

**Review by chinandrew — APPROVED** [review]
:shipit::shipit::shipit:

**Pull request merged**
