### PR TITLE
Fix smoother index drop

### PR DESCRIPTION
**Pull request by dshemetov**
Fixes a bug where the smoother would drop the index of the Pandas series given to it. The index is restored after smoothing. Base is #477 and contains #437, so should be merged after.

### CODE REVIEW

**Comment by krivard** [comment]
You have some conflicts here, but it's not on any files ostensibly edited by this PR so I don't really understand what's going on.

**Comment by dshemetov** [comment]
That is strange. Any ideas for how to diagnose?

**Comment by krivard** [comment]
Merge with/rebase onto main and see what happens?

**Comment by dshemetov** [comment]
Ok that seemed to fix it?

**Comment by dshemetov** [comment]
I think I can clean up this commit log, let me try rebasing these PRs I made last night.

**Comment by dshemetov** [comment]
Waaay cleaner now: 4 PRs, 4 commits. Thanks Katie, this was a nice learning experience!

**Review by krivard — APPROVED** [review]
This looks okay to me but I'm a very beginner pandas user so I'm looping in Andrew

**Pull request merged**
