### PR TITLE
Add hhs and nation to DV

### PR DESCRIPTION
**Pull request by chinandrew**
### Description
Replaces #616.

Cherrypicked  588f805 and made one small typo change.

### Changelog
Itemize code/test/documentation changes and files added/removed.
- Added functions for mapping counties to new geos, following same pattern as other geos (yes, there's some code duplication. figure we can refactor separately.)

### Fixes 
-

### CODE REVIEW

**Comment by krivard** [comment]
`too-many-branches`, alas

**Comment by chinandrew** [comment]
> `too-many-branches`, alas
:( converted if/else block it to a dict for now.

**Comment by krivard** [comment]
@mariajahja if this is good we'll want to update the copy on the magic server once it's merged

**Review by mariajahja — APPROVED** [review]
Actual PR looks good and some quick checks for county/hrr/state line up with existing estimates. 

Noticed that there were some params.json changes from the version running on the magic server, but there some small adjustments needed (dropped f-strings prefixes and change from 60->70 days of updates). @krivard OK for me to open a separate PR for these?

**Comment by krivard** [comment]
@mariajahja yep, separate PR.

**Pull request merged**
