### PR TITLE
Add nation and HHS to USAFacts

### PR DESCRIPTION
**Pull request by chinandrew**
### Description
**Merge after #623**
Add HHS and nation to USAFacts

### Changelog
Itemize code/test/documentation changes and files added/removed.
- Add HHS and Nation to allowed constants
- Add test cases
- Update documentation

### Fixes 
- Fixes #(issue)

### CODE REVIEW

**Comment by krivard** [comment]
ah sorry, you ran into #623

**Comment by chinandrew** [comment]
> ah sorry, you ran into #623

For some reason I didnt see this comment until now. Sorry about that, resolve.

**Comment by chinandrew** [comment]
blocked by #708

**Review by krivard — APPROVED** [review]
lgtm

**Pull request merged**
