### PR TITLE
[CTIS] Change QSF differ to export diffs as CSV

### PR DESCRIPTION
**Pull request by nmdefries**
### Description
Export diffs in CSV format to make them more useful for documentation. Included fields: new and old wave number, type of change (item was added or removed, display logic changed, etc), item name, and internal Qualtrics ID for each item. Everything except new/old wave was in the old diff format too.

### Changelog
- `qsf-tools/qsf-differ.R`

### CODE REVIEW

**Review by capnrefsmmat — APPROVED** [review]
Looks good, I think. Do you have an example of the output file?

**Comment by nmdefries** [comment]
Sure, old output (for Wave 13 vs 12) is printed to the console, e.g.

```
 Added: item C17b (QID261)
 Added: item Signposting1 (QID268)
 Added: item Signposting5 (QID272)
 Added: item V17 (QID277)
 Added: item V17_month (QID278)
 Added: item V17_year (QID279)
 Added: item V2a (QID262)
 Added: item V2b (QID264)
 Added: item V2c (QID265)
 Added: item Vaccine_Text  (QID263)

 Removed: item B10b (QID156)
 Removed: item C6a (QID163)
 Removed: item I1 (QID235)
 Removed: item I2 (QID236)
 Removed: item V15c (QID223)
 Removed: item V2 (QID141)

 Question wording changed: item B2 (QID151)
```

and new output

[diff_12-13.csv](https://github.com/cmu-delphi/covidcast-indicators/files/8201366/diff_12-13.csv)

**Comment by capnrefsmmat** [comment]
Looks good, thanks. Some day, we may have a pretty useful suite of QSF tools to share...

**Comment by nmdefries** [comment]
@krivard This is ready to merge

**Pull request merged**
