### PR TITLE
Remove cds, emr_hosp, google_health

### LINKED ISSUE #384: Remove deprecated indicators cds and emr_hosp from repo.
Remove the directories for deprecated indicators. Tag the commit that does this for easy tracking.

### PR DESCRIPTION
**Pull request by chinandrew**
Closes #384 

Summary of changes:
- Delete the deprecated cds/, emr_hosp/, and google_health/ directories. 

I tagged this commit but I'm not sure how to view the tags on github. If anyone can verify please let me know.

### CODE REVIEW

**Comment by capnrefsmmat** [comment]
Note that you need `git push --tags` to actually push tags to a remote.

**Comment by krivard** [comment]
I led you astray: `google_health` is deprecated, but is still in production while we work on [the new GS indicator](https://github.com/cmu-delphi/covidcast-indicators/issues/270).

(also: [tags can be viewed here](https://github.com/cmu-delphi/covidcast-indicators/tags), & linked from the front page next to "63 branches")

**Comment by chinandrew** [comment]
> I led you astray: `google_health` is deprecated, but is still in production while we work on [the new GS indicator](https://github.com/cmu-delphi/covidcast-indicators/issues/270).

Does this mean we should hold off on deleting until then? Either by only deleting the other two or just waiting and deleting all 3 at once.


> (also: [tags can be viewed here](https://github.com/cmu-delphi/covidcast-indicators/tags), & linked from the front page next to "63 branches")

:+1: Thanks

**Comment by krivard** [comment]
@benjaminysmith @korlaxxalrok Thoughts? 

* Delete all 3 now, and freeze the `deploy-ght` branch so the production deployment stays in place. Possible footgun if someone forgets.
* Delete all 3 later, once GS is ready. Adds to the stack of things to remember to do later.
* Delete the other 2 now, delete GHT later once GS is ready. Adds to the stack of things to remember to do later (though might be a natural step of deploying GS)

**Comment by benjaminysmith** [comment]
>> Delete the other 2 now, delete GHT later once GS is ready. Adds to the stack of things to remember to do later (though might be a natural step of deploying GS)

I prefer this one. If it's not too much work to split, this sounds like the choice that requires least mental load.

**Comment by krivard** [comment]
Excellent, let's go with that then. @chinandrew you good to implement? Prefer force-updating the existing tag to adding a new one.

**Comment by chinandrew** [comment]
> Excellent, let's go with that then. @chinandrew you good to implement? Prefer force-updating the existing tag to adding a new one.

It may just be easier to delete the existing tag and adding a new one given that I have a self inflicted merge conflict. If there's a clean way around that let me know.

**Comment by chinandrew** [comment]
Tag updated and reused in #394

**Pull request closed without merging**
