### PR TITLE
Include random module assignment

### PR DESCRIPTION
**Pull request by nmdefries**
### Description
Process and save to microdata variable indicating if respondent was randomized to Module A or Module B.

### Changelog
- Create variable `module`, coded as A/B/`NA`, based on column `FL_23_DO`. Note that this column name may change in later survey waves.
- Add `module` variable to microdata output.
- Ask Qualtrics API for display order info.

### CODE REVIEW

**Review by capnrefsmmat — APPROVED** [review]
R code portion looks fine to me; I'll let @krivard look at the one line of Python

**Review by krivard — APPROVED** [review]
legit

**Comment by krivard** [comment]
is this urgent enough for a friday deploy, or hold off for monday in case something goes sideways?

**Comment by capnrefsmmat** [comment]
If we deploy Monday, we'll want to reissue the microdata files from this weekend (the first ones with Wave 11) so they have the module column added to them. Though I guess that will happen automatically, since the past few days get reissued.

**Comment by krivard** [comment]
deployed, ready for tomorrow morning. @nmdefries would you reissue the microdata?

**Pull request merged**
