### PR TITLE
Add bash initializer needed for temp environment

### PR DESCRIPTION
**Pull request by krivard**
### Description
Dangling change to Makefile so that we get the right Python when we run in the temporary production environment. Most systems won't need this. In tmp-prod, the rc file contains the following content:

```
scl enable rh-python38 bash
```

### Changelog
Itemize code/test/documentation changes and files added/removed.
- Makefile -- source an rc file when constructing the shell
- bash-init.sh.template -- empty; copy this to bash-init.sh to use

### CODE REVIEW

**Review by nmdefries — COMMENTED** [review]
My understanding is that this change, if `bash-init.sh` is not empty, runs all make targets in a new bash instance with some specified version of Python rather than using the version of Python already installed. And we need Python 3.8 specifically because of this line `python3.8 -m venv env` in the make `install-python` target.

Since we're using a docker container, couldn't we explicitly install Python 3.8 there instead? Of course, the approach implemented here is more flexible, since it doesn't require a docker container.

**Comment by krivard** [comment]
Clarification: this rc file is needed for the current execution environment on bigchunk-dev-02; it permits running a necessary setup command _before_ `source env/bin/activate`. Ultimately, the env python executable is still used, we're not trying to swap in a non-indicator-approved python version here. RedHat just needs us to give the OS a heads-up before we run a version of python other than the system version.

More information: https://developers.redhat.com/blog/2018/08/13/install-python3-rhel#software_collection_tips

**Comment by krivard** [comment]
(I anticipate the final containerized version won't need this rc file)

**Review by nmdefries — APPROVED** [review]
Got it and looks good!

**Pull request merged**
