### PR TITLE
Switch failing validation to if not statement 

### PR DESCRIPTION
**Pull request by neul3**
### Description
Bug Fix for Validator

### CODE REVIEW

**Comment by neul3** [comment]
Local tests are successful after removing `APIDataFetchError` from the imported errors.

**Comment by krivard** [comment]
is there a reason to leave it in?

**Comment by neul3** [comment]
I don't believe so.

**Comment by krivard** [comment]
Then we should remove it 🙂

**Review by krivard — APPROVED** [review]
👍

**Pull request merged**
