### PR TITLE
Add Quidel Ansible and params config for accessing the S3 bucket

### PR DESCRIPTION
**Pull request by korlaxxalrok**
### Description
Feature:

Adds the necessary Ansible vars/vault entries plus the prod params config so
that the indicator can interact with the S3 bucket.

### Changelog
Itemize code/test/documentation changes and files added/removed.
- Update prod params.
- Add Ansible bucket name variable.
- Add Ansible variable pointers to vault.
- Add Ansible Vault variables.

### CODE REVIEW

**Comment by korlaxxalrok** [comment]
@jingjtang I also removed the email settings. I made an assumption that we aren't checking the mail account anymore, but do those need to stay in the params?

**Comment by jingjtang** [comment]
> @jingjtang I also removed the email settings. I made an assumption that we aren't checking the mail account anymore, but do those need to stay in the params?

The email settings are not needed anymore. They should be removed from `params` settings.

**Comment by korlaxxalrok** [comment]
@jingjtang If it looks good to you I think this is ok to merge now.

**Review by jingjtang — APPROVED** [review]
lgtm

**Pull request merged**
