### PR TITLE
Refactor Usafacts to use smoothing utils

### LINKED ISSUE #428: usafacts - smoothing refactor
Refactor usafacts to use new smoothing utilities

### PR DESCRIPTION
**Pull request by chinandrew**
Closes #428 

Summary of Changes:
- Update USAFacts to use the utils smoother utility
- Delete old smooth file and test

### CODE REVIEW

**Comment by chinandrew** [comment]
blocked by #437

**Comment by chinandrew** [comment]
unblocked

**Comment by chinandrew** [comment]
blocked by new bug with indices on smoothing

**Comment by krivard** [comment]
@chinandrew sorry I unblocked without seeing the full thread. Was the smoothing indices bug fixed by #478 ?

**Comment by chinandrew** [comment]
> @chinandrew sorry I unblocked without seeing the full thread. Was the smoothing indices bug fixed by #478 ?

Yup

**Pull request merged**
