### PR TITLE
Discontinue unweighted survey signals

### PR DESCRIPTION
**Pull request by nmdefries**
### Description
We currently report in the API weighted and unweighted versions of every survey signal. This roughly doubles the resources required to produce and store the survey data. However, due to reduced urgency at this point in the pandemic, unweighted signals that are available slightly sooner don't add much value when more-accurate weighted signals are also available.

[FB Asana task with more info](https://app.asana.com/0/1199704294865989/1201238136692629/f)

### Changelog
- Remove all unweighted signals (those using uniform weights) from indicator lists in `binary.R` and `count.R`.
- Suppress removed signals in sirCal ansible and package params templates.

Note: This is waiting for feedback from API users to see if anyone still has a strong need for particular unweighted signals. Aiming to deploy Nov 30.

### CODE REVIEW

**Comment by capnrefsmmat** [comment]
I don't recall an existing email to the API list about this; @krivard mind if I send something to the API list proposing the discontinuation and asking for feedback?

**Comment by nmdefries** [comment]
Nobody on the survey mailing list has complained about this, so we're good to go there. We should merge/deploy this after the standard error reissue is done so that unweighted signals are backfilled too.

**Comment by nmdefries** [comment]
@capnrefsmmat Reminder to review.

**Review by capnrefsmmat — APPROVED** [review]

**Comment by nmdefries** [comment]
Wait to merge until https://github.com/cmu-delphi/covidcast-indicators/pull/1065 is merged and standard errors are backfilled.

**Pull request closed without merging**
