### PR TITLE
Add to Jenkins list of indicators to build

### PR DESCRIPTION
**Pull request by korlaxxalrok**
### Description
Fix:

Add `covid_act_now` to Jenkinsfile list.

### Fixes

### CODE REVIEW

**Comment by korlaxxalrok** [comment]
@krivard I forgot this in my first PR.

**Comment by krivard** [comment]
Looks like this indicator hasn't been added to CI either. Should we do that before merging this PR to make sure all checks pass?

**Comment by korlaxxalrok** [comment]
Yeah, good call. Just added.

**Comment by krivard** [comment]
well lookit that 😉

**Comment by krivard** [comment]
@eujing would you take a look? we need `make test lint` to pass before we can deploy the CAN indicator.

**Comment by eujing** [comment]
I fixed the `wip_signal` error and the other linting errors, `make test lint` passes on my side now.

**Review by krivard — APPROVED** [review]
👍

**Pull request merged**
