### PR TITLE
Finish quidel geo util refactor

### PR DESCRIPTION
**Pull request by chinandrew**
### Description
For some reason quidel_covidtest was refactored but quidel wasn't finished. Basically just copied the changes from https://github.com/cmu-delphi/covidcast-indicators/commit/b39d55f58d14389d6aadc3e2571f125bd13d82a8

### Changelog
Itemize code/test/documentation changes and files added/removed.
- Update geo_map to use geo utils by taking existing code from quidel_covidtest
- Change function calls to match new signature
- Fix tests

### Fixes 
- Fixes #(issue)

### CODE REVIEW

**Comment by jingjtang** [comment]
@chinandrew I got these for linting. No big problems.
```
************* Module delphi_quidel.run
delphi_quidel/run.py:7:0: W0611: Unused join imported from os.path (unused-import)
delphi_quidel/run.py:9:0: W0611: Unused pandas imported as pd (unused-import)
************* Module delphi_quidel.pull
delphi_quidel/pull.py:65:0: C0301: Line too long (102/100) (line-too-long)
delphi_quidel/pull.py:314:0: C0301: Line too long (115/100) (line-too-long)
delphi_quidel/pull.py:405:0: C0301: Line too long (117/100) (line-too-long)
************* Module delphi_quidel.data_tools
delphi_quidel/data_tools.py:9:0: C0303: Trailing whitespace (trailing-whitespace)
delphi_quidel/data_tools.py:67:0: C0301: Line too long (109/100) (line-too-long)
delphi_quidel/data_tools.py:122:0: C0301: Line too long (112/100) (line-too-long)
delphi_quidel/data_tools.py:175:0: C0301: Line too long (105/100) (line-too-long)
delphi_quidel/data_tools.py:310:0: C0301: Line too long (102/100) (line-too-long)
```

**Comment by chinandrew** [comment]
@krivard informed me that the run-quidel branch already has these changes and just isn't in main yet, so I guess this may not be needed?

**Comment by jingjtang** [comment]
@chinandrew Oh, yes. I have finished the geo util refactor in run-quidel branch. Didn't realize that it is not in the main.

**Comment by krivard** [comment]
`run-quidel` has the merged flu+covid quidel pipeline, which has not been deployed, and iirc is blocked on deletion support since it will also remove a bunch of regions from the historical data record

**Comment by chinandrew** [comment]
is run-quidel what's currently deployed?

**Comment by jingjtang** [comment]
@chinandrew `quidel_covidtest` is the one that is deployed which is for covidtest only. `run-quidel` is for both covid test and flu test

**Comment by chinandrew** [comment]
ah, right. in that case I think this PR can be closed and we'll just figure out the run-quidel issue

**Pull request closed without merging**
