### PR TITLE
[fb-package] Report initial set of contingency tables

### PR DESCRIPTION
**Pull request by nmdefries**
### Description
The set of expanded aggregates doesn't include [all tables originally issued](https://github.com/cmu-delphi/covidcast-indicators/blob/13520851920611c2b00f9a5e5136f003184242c8/facebook/delphiFacebook/R/contingency_run.R) -- see the first ~160 lines; aggs that have been commented out are already covered in the new set. We want to continue reporting these, so add them back in, plus some supporting features.

### Changelog
- Report contingency tables from initial data issue not already reported.
- Switch numeric compute function to one that reports standard errors.
- Create function to create aggregates from all combinations of input groups, regions, and indicators.

### CODE REVIEW

**Comment by nmdefries** [comment]
@davidkretch I can't seem to officially request a review from you, but I'd appreciate if you could take a look at this and leave any comments/suggestions.

**Comment by davidkretch** [comment]
No problem! Will get to it later today.

**Comment by davidkretch** [comment]
Looks good to me and works for me too. I like the new `create_aggs_product`. I don't have any other comments. 👍

**Comment by nmdefries** [comment]
Thanks @davidkretch!

**Review by capnrefsmmat — APPROVED** [review]

**Pull request merged**
