### PR TITLE
Support upload of raceeth microdata in Makefile

### PR DESCRIPTION
**Pull request by nmdefries**
### Description
Put #1183 into production.

### Changelog
-  Add make target to upload race-eth microdata files to `protected-race-ethnicity-data/` dir. Runs as part of `pipeline` target.
- Add raceeth microdata dir to clean and tidy targets.
- Add `individual_raceeth_dir` and `produce_individual_raceeth` default settings to the template production params file.
- Turn on `produce_individual_raceeth` in the params make target.

### CODE REVIEW

**Comment by krivard** [comment]
Would you add the new keys to `params.json.template` and `params.json.production.template` please?

**Review by krivard — APPROVED** [review]
👍

**Comment by krivard** [comment]
Should I wait for Alex on this or go ahead and merge once it finishes building?

**Comment by capnrefsmmat** [comment]
Also note that whatever script runs `monthly-files.R` should also run it on the raceeth data each month, to produce monthly race/ethnicity rollups.

**Pull request merged**
