### PR TITLE
Fix CHNG output so that changes in startdate change which files are created, but nothing else

### LINKED ISSUE #1048: CHNG randomly losing track of data?
A weird thing:

* CHNG generates an empty file for day X, issue Y. This file fails ingestion.
* There is a successful file for day X, issue Z<Y, which has data.
* The raw data file processed for issue Y has strictly more counts than the raw data file processed for issue Z.

Example: There's a failed file for 20210226 from issue 20210503, but a successful one from issue 20210501. The failed file contains only the header, but the earlier successful file contains records for all states.
```
[krivard@delphi-master-prod-01 covidcast]$ find archive -name "20210226_state_smoothed_adj_outpatient_covid.*" -exec ls -l {} +
-rw-r--r--. 1 indicators indicators  26 May  3 13:16 archive/failed/chng/20210226_state_smoothed_adj_outpatient_covid.csv
-rw-rw-r--. 1 automation automation 524 May  1 23:00 archive/successful/chng/20210226_state_smoothed_adj_outpatient_covid.csv.gz
[krivard@delphi-master-prod-01 covidcast]$ wc -l archive/failed/chng/20210226_state_smoothed_adj_outpatient_covid.csv
1 archive/failed/chng/20210226_state_smoothed_adj_outpatient_covid.csv
[krivard@delphi-master-prod-01 covidcast]$ zcat archive/successful/chng/20210226_state_smoothed_adj_outpatient_covid.csv.gz |wc -l
55
```

The failed file was generated from the data drops labeled 20210502; the successful one from data drops labeled 20210430. Here's the diff:

```
[indicators@delphi-master-prod-01 changehc]$ diff <(zcat cache/20210430_Counts_Products_Covid.dat.gz |grep 20210226) <(zcat cache/20210502_Counts_Products_Covid.dat.gz |grep 20210226)
176c176
< 20210226,09003,87
---
> 20210226,09003,88
218c218
< 20210226,12086,337
---
> 20210226,12086,338
773a774
> 20210226,27007,3 or less
786c787
< 20210226,27053,50
---
> 20210226,27053,51
1001c1002
< 20210226,36029,63
---
> 20210226,36029,64
1003c1004
< 20210226,36033,13
---
> 20210226,36033,14
1132c1133
< 20210226,39035,163
---
> 20210226,39035,164
1163c1164
< 20210226,39103,24
---
> 20210226,39103,25
```

In no case does the new 20210502 file remove any counts for reference date 20210226, yet, an empty file was generated.

### PR DESCRIPTION
**Pull request by krivard**
### Description
The earliest date of each CHNG submission included only the header for each file, whereas past submissions had plenty of data for that date. This was in error. We're not sure why that's happening, but it's certainly true that changing the startdate and nothing else changes the number of rows in outputted files, which is bad.

Draft PR for group debugging.

I found https://github.com/cmu-delphi/covidcast-indicators/issues/1048, which is old, and was closed due to lack of any further information or clear negative effect. Now that we interpret the absence of a region as a deletion and propagate that event to the API, we need to fix it.

### Changelog
Itemize code/test/documentation changes and files added/removed.
- TBD

### Fixes 
- Fixes #1048

### CODE REVIEW

**Comment by rumackaaron** [comment]
It looks like the SQL change is as simple as what you said. This could be updated in the `chng` reissues, but we are only reissuing data up to issue date `2021-02-21` or maybe `2021-03-30`. We'd still need to update the historical data for more recent issues.

**Comment by rumackaaron** [comment]
Cool, I set the offset to 0. And I'm sure this is obvious, but we should tell people since this will change all indicator values

**Comment by rumackaaron** [comment]
@krivard Roni mentioned to me today that the CHNG signal is still not online. Is there anything I still need to do?

**Comment by krivard** [comment]
I totally missed that commit and thought this was still pending since it's still labeled as draft. 😣  Let me flip the status so it runs tests

**Comment by krivard** [comment]
Looks like something is fishy in the tests -- take a look?

**Comment by rumackaaron** [comment]
The tests keep passing locally for me, I don't know what else to do

**Comment by rumackaaron** [comment]
Somehow there's a default date_col="timestamp" that isn't getting overridden to "date" in Geomapper, but no matter how I set the defaults locally, the tests always pass.

**Comment by rumackaaron** [comment]
@krivard ready to merge

**Pull request merged**
