### PR TITLE
Fix CPR data duplication and missing nation SE and n columns

### PR DESCRIPTION
**Pull request by nmdefries**
### Description
Fix
- State to nation aggregation drops sample size and standard error columns. Add them back explicitly.
- A small number of daily reports were published multiple times (with different asset ids), which causes overcounting for some signals. Deduplicate rows.

### Changelog
- `pull.py`

### CODE REVIEW

**Review by krivard — APPROVED** [review]

**Comment by krivard** [comment]
are there more things to add to this pr or is it ready to go?

**Comment by nmdefries** [comment]
I'm going to add an assert about each timestamp-geo id having a single row, so we'll get an error message if multiple daily reports were published for a given day *and* they don't match.

**Comment by nmdefries** [comment]
Okay, this is ready

**Review by krivard — APPROVED** [review]
🪨 ⭐

**Pull request merged**
