### PR TITLE
Add codebook descriptions for new Wave 13 items

### PR DESCRIPTION
**Pull request by nmdefries**
### Description
Update `qsf-tools` item descriptions file for Wave 13.

### Changelog
- `item_shortquestion_map.csv`

### CODE REVIEW

**Comment by nmdefries** [comment]
@capnrefsmmat ping for review

**Comment by capnrefsmmat** [comment]
Does this need to be updated given #1521?

**Comment by nmdefries** [comment]
There was a merge conflict between the two PRs, but besides that they are compatible.

**Comment by capnrefsmmat** [comment]
Sorry, to be more specific, does this file not need anything for V2d?

**Comment by nmdefries** [comment]
I added the short description for V2d into the "bodge V2d" PR.

**Review by capnrefsmmat — APPROVED** [review]
👍

**Comment by nmdefries** [comment]
@krivard This is ready to merge.

**Pull request merged**
