### PR TITLE
[DRAFT/TEST] try out CI config for testing packages

### PR DESCRIPTION
**Pull request by chinandrew**
Just testing out some github actions, don't merge. cc @korlaxxalrok @benjaminysmith @krivard.

Aside from that issue, something like this should satisfy the testing need for PRs. See checks below for summaries. I'm only running 2 indicators and the utils package at the moment for demonstration.

I've brought up the subject of costs for this before. Even though it's not super high it's still worth keeping in mind. If it is an issue, one thing we could do if we move to a gitflow branching approach is only run tests on merge with the develop branch. This way we can catch things before they hit main without needing to run 10 checks each time someone commits changes to a PR. It unfortunately gives up the ability to see all the checks passing in PR phase. There may be some intermediate approach where only checks on altered packages are run, but that's going to be a bit more complex and not foolproof (e.g. if i change the utils i can still break other packages).

I'm still trying to figure out the linter. On some packages (usafacts), I hit this [weird recursion error](https://stackoverflow.com/questions/36496192/pylint-infinite-recursion-in-astriod-package) that I can't reproduce locally and have been unable to debug.

### CODE REVIEW

**Comment by chinandrew** [comment]
Also just went through the `jenkins` folder and that seems perfectly fine to extend to this application as well. I don't personally have any experience with it though.

**Comment by korlaxxalrok** [comment]
@chinandrew This looks promising 👍 

>There may be some intermediate approach where only checks on altered packages are run

Is this referring to being able to run CI actions based on what is being "worked on" (ie changes to a single indicator)? That would be pretty useful, and was something I was thinking about trying to figure out for Jenkins.

**Comment by chinandrew** [comment]
> @chinandrew This looks promising 
> 
> > There may be some intermediate approach where only checks on altered packages are run
> 
> Is this referring to being able to run CI actions based on what is being "worked on" (ie changes to a single indicator)? That would be pretty useful, and was something I was thinking about trying to figure out for Jenkins.

Yea, so something like changing the code for `cdc_covidnet` doesnt run the `safegraph` tests. We just have to be careful that utility changes always run all indicators.

**Comment by chinandrew** [comment]
Alright linting is in place now (which is why checks aren't passing). See #333  for more details.

**Comment by chinandrew** [comment]
opening a new pr in #449

**Pull request closed without merging**
