### PR TITLE
[Fix] Make Smoother "identity" smoother a true no-op by default (no impute)

### PR DESCRIPTION
**Pull request by dshemetov**
### Description
Currently, the identity smoother imputes nan values using the "savgol" smoother. This was the intended behavior for other smoothers (since not imputing while smoothing would lead to nan propagation), but the intention for the identity smoother is to be a true no-op by default. This fixes that issue.

### Changelog
Change the default argument handling: the default for "identity" is no imputation, while the default for anything else is "savgol". User-supplied impute arguments are handled normally.

### Fixes 
- Probably helps #1077. 
- May change the JHU and USAFacts raw signals (difference plots incoming).

### CODE REVIEW

**Comment by krivard** [comment]
Fix your tests please

**Comment by dshemetov** [comment]
Done!

**Comment by dshemetov** [comment]
Don't merge yet, I will need to update Andrew's fix

**Comment by chinandrew** [comment]
> Don't merge yet, I will need to update Andrew's fix

My fix? If you're referring to #1077, I just specified `impute_method = None`, which should work with both this PR and what is currently in main. Perhaps updating it to "identity" or removing the impute_method kwarg would be a bit cleaner once this is merged, but functionally the same.

**Comment by dshemetov** [comment]
You're right, we don't have to update that. Ready to merge whenever.

**Review by krivard — APPROVED** [review]
LGTM!

**Pull request merged**
