### PR TITLE
Refactor CHC to use smoothing utils

### LINKED ISSUE #430: changehc - smoothing refactor
Refactor changehc to use smoothing utility

### PR DESCRIPTION
**Pull request by chinandrew**
Closes #430 

Summary of Changes:
- Update Change to use new smoothing utils
- Update test to smooth on test data

### CODE REVIEW

**Comment by chinandrew** [comment]
blocked by #437

**Comment by rumackaaron** [comment]
I'm getting some linting errors, but I assume they were fixed by #463

**Comment by rumackaaron** [comment]
The refactor itself looks good and the tests pass

**Review by rumackaaron — APPROVED** [review]

**Comment by chinandrew** [comment]
Just merged main in, passing on my end now.

**Comment by rumackaaron** [comment]
Passing for me too

**Pull request merged**
