### PR TITLE
[Backfill corrections] Efficient date handling and rolling averages

### PR DESCRIPTION
**Pull request by nmdefries**
### Description
Various changes to make modeling/predicting faster. The main changes are:

- Keep date fields (`time_value`, `issue_date`) in string format. Explicitly convert to date when required. This reduces the (large) number of implicit date-to-string conversions happening in other functions.
- Replace `zoo::rollmeanr` with `RcppRoll::roll_mean` for speed. Unlike most other fast rolling average functions available in R (e.g. `stats::filter`), `RcppRoll::roll_mean` uses the same more-precise method as `zoo`; the speedup is only because the new function is implemented in C++.

Modeling with these changes is 20% faster than after https://github.com/cmu-delphi/covidcast-indicators/pull/1802 changes and 33% faster overall. The test example is smaller than what would be used in production.

### CODE REVIEW

**Review by jingjtang — APPROVED** [review]
LGTM

**Review by jingjtang — APPROVED** [review]
LGTM

**Comment by nmdefries** [comment]
@korlaxxalrok This is ready to merge

**Comment by nmdefries** [comment]
@krivard This is ready to merge

**Pull request merged**
